# Generated by Django 4.0.5 on 2022-07-20 20:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
