# Generated by Django 4.0.5 on 2022-07-20 21:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaFinalApp', '0002_publicaciones_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='body',
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
